### ISSUE TITLE
Changing the organization's name to CQuIC

### ISSUE THREAD

**Issue by i2000s** [CQuIC/qcircuit#21]
Dear qcircuit users,

I am glad to inform you that GitHub finally agrees to grant us the username of ***CQuIC*** for our organization! That means we don't need to use the strange url *http://CQuIC-GitHub.GitHub.io* for our organization's website; instead, we will use *http://CQuIC.github.io* simply (you can use all little letters)! All the other long names of this organization can be shorten and meaningful for the future. I had registered this organization using the ***CQuIC-GitHub*** name is just because there was a ***cquic*** user name registered before me. Now the user ***cquic*** has been dormant for ~40 months so that GitHub can delete that account legally and grant us the shorter user name for the org. I guess no one will object this change.

However, there are a few workarounds to adapt for everyone who is using the ***Qcircuit*** repo affiliated to the org:

1. Please check if you have linked this CQuIC-GitHub organization or *qcircuit* repo to anywhere online. If so, you may need to replace the CQuIC-GitHub to the new name CQuIC in the URLs. I will make the change on the JuliaQuantum's website, the UNM departmental website and my website along with the org's internal docs. @Travis-S Travis will update the Qcircuit links in CTAN (and possibly the org's website as well?).

2. If you are using this repository in git, your remote URL should also be adapted. You need to replace the CQuIC-GitHub with CQuIC in the url of your remote. You can either do it in the hidden git configuration file on your local git repository, or you can use the `git remote set-url` command to change the urls. Check [here](https://help.github.com/articles/changing-a-remote-s-url/) for the instruction.

I will ask GitHub people to switch the organization's name to CQuIC officially on Friday (Feb 26). After the switch, if you don't adapt point 2 above, you will not be able to push/fetch changes to/from the remote repository as before.

Let me know if you have any concerns or technical questions. I will keep you posted once the switch of names is done. Sorry for bothering you.

Cheers,
Qi

**Comment by i2000s** [comment]
Just to let you know that the name of the organization has been switched. Website CQuIC.github.io works online! The qcircuit link in CTAN should be corrected on the next release of the package. I will close this issue in a week. In the mean time, let me know if you encounter any problems.

Thanks,
Qi

**Comment by Travis-S** [comment]
I've updated the README and the tutorial file. @i2000s, is it possible to update the [PandA page](http://physics.unm.edu/CQuIC/Qcircuit/) with the correct link?

**Comment by i2000s** [comment]
@Travis-S I will do the PandA page later this week, if they didn't change the password in the pass month.

**Comment by i2000s** [comment]
Links have been updated on the PandA server: http://physics.unm.edu/CQuIC/Qcircuit/. Cheers!
