### ISSUE TITLE
Migrating the old Qcircuit page on the UNM physics server

### ISSUE THREAD

**Issue by i2000s** [CQuIC/qcircuit#23]
As CQuIC is migrating its website (formerly at http://physics.unm.edu/CQuIC to http://cquic.unm.edu/), the Qcircuit page has to be redirected to the http://cquic.unm.edu/resources/ page or elsewhere. Beside the [Resources page](http://cquic.unm.edu/resources/), we can have an independent page using Github pages. I have submitted a migration ticket to the UNM IT people to have a permanent server redirect set up, but let me know if you have any other thoughts or requirements.

@CQuIC/cquic-orgweb @sflammia

**Comment by Travis-S** [comment]
If UNM IT doesn't want to set up a permanent redirect, it's fine to just have the link from the CQuIC website to this repo.

**Comment by Travis-S** [comment]
Some links which should be fixed:

* https://github.com/CQuIC-GitHub/qcircuit (simple rename)
* http://physics.unm.edu/CQuIC/Qcircuit/Qcircuit.tex (get rid of it)
* https://github.com/CQuIC-GitHub/qcircuit/issues (simple rename)

On a completely unrelated note, could we change the name on the "Resources" page to ``qcircuit``, instead of ``q-circuit``?

**Comment by i2000s** [comment]
I have fixed those links. `qcircuit` looks better than `q-circuit` for me, and I have updated the [CQuIC page](http://cquic.unm.edu/resources/) accordingly for your preview.

The UNM IT staffs have created a permanent link for our old website. I think it's safe to leave the page there without worrying about future updates.

**Comment by Travis-S** [comment]
Currently, the link back to the [old qcircuit website](http://physics.unm.edu/CQuIC/Qcircuit/Qcircuit.tex)  gives 404 error. To clarify, at some point that URL will redirect/be updated?

**Comment by i2000s** [comment]
I have emailed Leanne to check what's going on. It was working last time
when I checked it.

I suggest not to use the link related to the physics server, because no
one is going to maintain it any more, and the physics server has been
hacked recently (the password is even not changed afterwards).

**Comment by Travis-S** [comment]
The link has been fixed. I don't think we should direct anyone to it, because it's just a download of what is now an out-of-date file.

**Comment by i2000s** [comment]
Yeah, Tom has fixed it this morning. We have linked the Github repo on that page for new users. So, we will leave it there as it is, and de-appreciate the link to future usage. @Travis-S Feel free to close this issue if you don't have any other comments. Thank you!
