### ISSUE TITLE
About qm notation

### ISSUE THREAD

**Issue by yuttai** [CQuIC/qcircuit#25]
In order to match the delimiters, maybe the qm symbols should define like this?

`\DeclareOption{qm}{`
`\newcommand{\ip}[2]{\ensuremath{\left\langle{#1}\middle\vert{#2}\right\rangle}}`
`\newcommand{\melem}[3]{\ensuremath{\left\langle{#1}\middle\vert{#2}\middle\vert{#3}\right\rangle}}`
`\newcommand{\expval}[1]{\ensuremath{\left\langle #1 \right\rangle}}`
`\newcommand{\op}[2]{\ensuremath{\left\vert{#1}\middle\rangle\middle\langle{#2}\right\vert}}`
`}`

**Comment by Travis-S** [comment]
Suggestions are incorporated in release 2.5.3. Closing this issue.
