### ISSUE TITLE
Proper way to do equality between circuits?

### ISSUE THREAD

**Issue by rmonat** [CQuIC/qcircuit#26]
Hi,

I would like to write that two quantum circuits C1 and C2 are equal, but with the equal sign at the mid-height circuit C1. Is there any way to do that?

Thank you.

**Comment by Travis-S** [comment]
Hey @rmonat, just wanted to let you know I saw this and will think about it some. Is this something which needs to be solved soon-ish?

**Comment by rmonat** [comment]
Thank you, @Travis-S. No, I just saw a conference paper with that kind of equalities and was unable to reproduce it, but it's nothing urgent!

**Comment by Travis-S** [comment]
Would you mind providing a link to the paper in question? If it's on the arXiv, and they did the qcircuit figures in the paper itself, we might be able to find it there.

**Comment by rmonat** [comment]
Here is the paper: http://www.cs.ox.ac.uk/people/samuel.staton/papers/popl2015.pdf. There is an example at the bottom of page 2.

**Comment by Travis-S** [comment]
@rmonat My mistake on not following up with this sooner! You can use qcircuit figures inside LaTeX's mathematical environments; so to make the figure you referenced, you could do this

```
\[
\Qcircuit @C=1em @R=.7em {
      & \gate{X} & \qw} 
=
\Qcircuit @C=1em @R=.7em {
      & \gate{X} & \qw}
\]
```

which produces this output:
![circuit](https://cloud.githubusercontent.com/assets/6274641/25630785/89909b2a-2f2b-11e7-8297-4ccfdbfa03d4.png)

In principle, this idea could be extended, say using the ``align`` environment, if you had several identities you wanted to display.

If this addresses your question, let me know, and I'll close this issue.

**Comment by rmonat** [comment]
This solves my problem, thank you!

**Comment by malbergo** [comment]
How might you do this so as to get a two row circuit equality? When I do it, the equals sign remains high up:


![image](https://user-images.githubusercontent.com/6062598/57157503-dd892300-6dae-11e9-953d-f10479c29fae.png)

Code:
```
\[
\Qcircuit @C=1em @R=1.5em {
& \multigate{1}{\mathcal{G(\theta,\phi)}} & \qw  \\
& \ghost{G(\theta,\phi)} & \qw  \\
}
=
\Qcircuit @C=1em @R=1.5em {
& \multigate{1}{\mathcal{G(\theta,\phi)}} & \qw  \\
& \ghost{G(\theta,\phi)} & \qw \\
}
\]
```

**Comment by zzwxy** [comment]
> How might you do this so as to get a two row circuit equality? When I do it, the equals sign remains high up:
> 
> ![image](https://user-images.githubusercontent.com/6062598/57157503-dd892300-6dae-11e9-953d-f10479c29fae.png)
> 
> Code:
> 
> ```
> \[
> \Qcircuit @C=1em @R=1.5em {
> & \multigate{1}{\mathcal{G(\theta,\phi)}} & \qw  \\
> & \ghost{G(\theta,\phi)} & \qw  \\
> }
> =
> \Qcircuit @C=1em @R=1.5em {
> & \multigate{1}{\mathcal{G(\theta,\phi)}} & \qw  \\
> & \ghost{G(\theta,\phi)} & \qw \\
> }
> \]
> ```
\[
You can use  \raisebox
\Qcircuit @C=1em @R=1.5em {
& \multigate{1}{\mathcal{G(\theta,\phi)}} & \qw  \\
& \ghost{G(\theta,\phi)} & \qw  \\
}
 \raisebox{-1.1em}{=}
\Qcircuit @C=1em @R=1.5em {
& \multigate{1}{\mathcal{G(\theta,\phi)}} & \qw  \\
& \ghost{G(\theta,\phi)} & \qw \\
}
\]

**Comment by evmckinney9** [comment]
I could not get this example to work using \raisebox. The way I do it is by manually adding an additional row for the equal sign to live in (needed if you have an even number of wires)

```latex
\Qcircuit @C=1.0em @R=0.4em @!R {
	 	& \multigate{2}{\mathrm{U_t}} & \qw & & & \gate{\mathrm{U}} & \multigate{2}{2Q} & \dots & & \multigate{2}{2Q} & \gate{\mathrm{U}} & \qw
	 	\\
	 	& & & \push{\rule{0em}{0em}\!\!\!\!\approx\!\!\!\!\rule{0em}{0em}}
	 	\\
	 	& \ghost{\mathrm{U_t}} & \qw & & & \gate{\mathrm{U}} & \ghost{2Q} & \dots & & \ghost{2Q} & \gate{\mathrm{U}} &\qw\\
}
```
![output-onlinepngtools](https://github.com/CQuIC/qcircuit/assets/47376937/22bc3e93-81d8-496b-84a6-f77ed608c5af)
