### ISSUE TITLE
Integrate qCircuit diagrams with LaTeX figures - captioning

### ISSUE THREAD

**Issue by Hosseinyeganeh** [CQuIC/qcircuit#28]
Hi
how I can add caption on circuit

**Comment by Travis-S** [comment]
+Hosseinyeganeh, you can wrap a latex figure object around qcircuit:

```
\begin{figure}[h]
\[ \Qcircuit @C=1em @R=.7em {
      & \gate{X} & \qw
}\]
\caption{My caption}
\label{My label}
\end{figure}
```

If this addresses your concern, please let me know, and I'll close this issue.
