### ISSUE TITLE
Label multi-qubit output states

### ISSUE THREAD

**Issue by Emieeel** [CQuIC/qcircuit#29]
As the output qubits are often entangled after the circuit, I would like to label the output. How do I label multi-qubit output states? I can't seem to find it anywhere in the tutorial.

**Comment by Travis-S** [comment]
One solution (based off of a document I found [here](http://www2.warwick.ac.uk/fac/sci/physics/research/cfsa/people/pastmembers/charemzam/pastprojects/)) is to use the `gategroup` command, like this:

```
\[
\Qcircuit @C=2em @R=.5em{
& \qw & \\     
& \qw & \ket{\psi}\\     
& \qw & \\
{\gategroup{1}{2}{3}{2}{1.75em}{\}}}
}
\]
```

which produces this output
![screenshot from 2017-05-21 19-22-32](https://cloud.githubusercontent.com/assets/6274641/26289176/dce8d0e2-3e5a-11e7-9de3-2a1adface0d1.png)

`\gategroup` is called as `\gategroup{start row}{start column}{end row}{end column}{twice the margin}{grouping symbol}`; above, I told `qcircuit` to start at the first row, second column, and to finish at the third row, also in the second column. The use of the braces around the `gategroup` call are to suppress an error; see [this StackOverflow post](https://tex.stackexchange.com/questions/233566/illegal-parameter-number-error-using-underbrace-in-qcircuit-environment).

If you wanted to push `\ket{\psi}` further to the right, you could use the `\rstick{}` command: `\rstick{\ket{\psi}}`.

If this addresses your question, let me know, and I'll close this issue.

**Comment by WolfLink** [comment]
This doesn't really work if you have an even number of qubits in your multi-qubit state.

**Comment by Antonio-Gonzalez-Gomez** [comment]
Late reply, but I had a similar problem until I realized you can use an extra column and \dstick in those cases:
```
\Qcircuit @C=1em @R=1em {
  \lstick{\ket{0}} \qw & \gate{H} & \ctrl{1} & \qw & & 
  \dstick{\ket{\Psi^+}}
  \gategroup{1}{4}{2}{4}{.7em}{\}} \\
  \lstick{\ket{0}} \qw & \qw & \targ & \qw
    }
```
![image](https://github.com/CQuIC/qcircuit/assets/61906376/7e53d4d3-2e8e-4816-8c0a-138c2f4ed0c3)
