### ISSUE TITLE
Can you add multigate with classical wire incoming.

### ISSUE THREAD

**Issue by LogicFan** [CQuIC/qcircuit#36]
Here is the code for cmultigate
\newcommand{\cmultigate}[2]{*+<1em,.9em>{\hphantom{#2}} \POS [0,0]="i",[0,0].[#1,0]="e",!C *{#2},"e"+UR;"e"+UL **\dir{-};"e"+DL **\dir{-};"e"+DR **\dir{-};"e"+UR **\dir{-},"i" \cw}
    % Same as multigate but with a classical incoming wire

**Comment by Travis-S** [comment]
Could you please for this repository and open a pull request with this change?
